"""mkdocs build hook: caption card thumbnails in the lightbox and link to their pages.

Card metadata lives in ``card-metadata.json`` (next to ``mkdocs.yml``), keyed by the
image's path relative to ``docs/``. For each gallery thumbnail whose image is in the
manifest, this hook adds a ``data-title`` to the wrapping ``<a>``. Lightbox2 renders
that ``data-title`` as the caption under the enlarged card (``sanitizeTitle`` is off,
so the caption may contain HTML), and we end it with a link to the card's standalone
page (generated by ``gen_cards.py``).

Searchability itself is handled by those generated pages, not here: their text is
visible, so mkdocs indexes each card as its own result and mkdocs-material can
highlight matches on the page. This hook only wires the gallery up to them.
"""

import html
import json
import os
import posixpath
import re
from urllib.parse import unquote

from mkdocs.utils import get_relative_url

_MANIFEST = {}
_IMG_SRC = re.compile(r'<img\b[^>]*?\bsrc="([^"]+)"')
# A gallery thumbnail: <a ...><img ...></a>. Captures the <a> attributes and the
# inner <img> so we can re-emit the anchor with an added data-title.
_ANCHOR_IMG = re.compile(r"<a\b(?P<attrs>[^>]*)>(?P<inner>\s*<img\b[^>]*?>\s*)</a>", re.S)


def _manifest_path(config):
    return os.path.join(os.path.dirname(config["config_file_path"]), "card-metadata.json")


def on_pre_build(config, **kwargs):
    # Reload every build so `mkdocs serve` picks up edits to card-metadata.json.
    global _MANIFEST
    try:
        with open(_manifest_path(config), encoding="utf-8") as fh:
            _MANIFEST = json.load(fh)
    except FileNotFoundError:
        _MANIFEST = {}


def on_serve(server, config, builder, **kwargs):
    # card-metadata.json lives outside docs/, so mkdocs doesn't watch it by default.
    server.watch(_manifest_path(config))
    return server


def _slug(text):
    # Keep in sync with _slug in gen_cards.py, which names the card pages we link to.
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "card"


def _text_values(value):
    """Yield every non-empty string/number leaf of a metadata value, in order."""
    if isinstance(value, bool):
        return
    if isinstance(value, str):
        stripped = value.strip()
        if stripped:
            yield stripped
    elif isinstance(value, (int, float)):
        yield str(value)
    elif isinstance(value, dict):
        for item in value.values():
            yield from _text_values(item)
    elif isinstance(value, list):
        for item in value:
            yield from _text_values(item)


def _card_href(name, page, files):
    src = "cards/" + _slug(name) + ".md"
    found = files.get_file_from_path(src)
    target = found.url if found is not None else "cards/" + _slug(name) + "/"
    return get_relative_url(target, page.file.url)


def _caption_attr(name, values, card_href):
    esc = lambda s: html.escape(s, quote=False)
    rest = list(values)
    if name in rest:
        rest.remove(name)
    parts = [f"<strong>{esc(name)}</strong>"]
    if rest:
        parts.append(esc(" — ".join(rest)))
    parts.append(f'<a class="lb-card-link" href="{card_href}">Open card page →</a>')
    caption = "<br>".join(parts)
    # data-title is decoded twice before it is shown: once when the browser parses
    # the attribute, then again when Lightbox re-injects it via jQuery .html(). This
    # second escaping of & and " (on top of the text escaping above) survives both
    # passes, so real card text containing & or " renders instead of breaking the
    # caption. Do not collapse it into a single escape.
    return caption.replace("&", "&amp;").replace('"', "&quot;")


def on_page_content(html_content, page, config, files, **kwargs):
    if not _MANIFEST:
        return html_content

    url_dir = posixpath.dirname(page.file.url)

    def caption_anchor(match):
        attrs = match.group("attrs")
        inner = match.group("inner")
        if "data-title" in attrs:  # respect an author-provided caption
            return match.group(0)
        src_match = _IMG_SRC.search(inner)
        if not src_match:
            return match.group(0)
        docs_path = posixpath.normpath(posixpath.join(url_dir, unquote(src_match.group(1))))
        meta = _MANIFEST.get(docs_path)
        if not meta:
            return match.group(0)
        values = list(_text_values(meta))
        if not values:
            return match.group(0)
        name = meta.get("name") or values[0]
        data_title = _caption_attr(name, values, _card_href(name, page, files))
        return f'<a{attrs} data-title="{data_title}">{inner}</a>'

    return _ANCHOR_IMG.sub(caption_anchor, html_content)
